version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    env_file:
      - ./.env
    volumes:
      - rabbitmq:/var/log/rabbitmq
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
